# Site Info
title: BETTER ME
tagline: '더 나은 나를 위한 노력'
description: "TO BECOME A BETTER PERSON"
url: http://bettermesol.github.io
logo: '/public/logo.png'
encoding: utf-8

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty
version: 1.0.0

# About/contact
author:
  name: Mesol Yoon
  description: 더 <strong>나</strong>은 <strong>나</strong>를 위하여 <strong>나</strong>아가는 중
  gravatar: '/public/logo.png' # md5 hash of your email address
  contact:
    linkedin:  https://www.linkedin.com/in/mesol-yoon-468346129/
    github:    https://github.com/bettermesol
    #facebook:  <hide>
    #twitter:  <hide>
    #weibo:    <hide>
    email:     mailto:mysky0313@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Contents:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: https://bettermesol.github.io/public/img/picture.JPG
  caption: # caption, if any

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: #'UA-12345678-9' # leave blank if you don't want google analytics
disqus_short_name: #'abc-github-io' # leave blank if you don't want disqus

